name: is_tv
description: Flutter plugin to check if current device is a Television.
version: 0.0.2+4

repository: https://github.com/imrhk/is_tv
issue_tracker: https://github.com/imrhk/is_tv/issues

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.litedevs.is_tv
        pluginClass: IsTVPlugin
      ios:
        pluginClass: IsTVPlugin
      linux:
        pluginClass: IsTVPlugin
      macos:
        pluginClass: IsTVPlugin
      windows:
        pluginClass: IsTVPluginCApi
      web:
        pluginClass: IsTVWeb
        fileName: is_tv_web.dart
